version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./storage:/app/storage
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-network

  upload-service:
    build:
      context: ./upload-service
      dockerfile: Dockerfile
    volumes:
      - ./storage:/app/storage
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-network

  processing-service:
    build:
      context: ./processing-service
      dockerfile: Dockerfile
    volumes:
      - ./storage:/app/storage
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-network

volumes:
  rabbitmq_data:

networks:
  microservices-network:
    driver: bridge